# setxkbmap -option grp:lshift_lalt_toggle us,eg

dbus-update-activation-environment --all
gnome-keyring-daemon --start --components=secrets

sh ~/src/script/setup_multi_monitores.sh

sxhkd &
slstatus &

redshift -O3500; xset r rate 300 50; exec dwm
